Mergin feature branch into master branch
ositaadimma/News-week-clone pull request #1
Opened 2020-09-18 12:50 UTC by guillainbisimwa

- created linters 
- Used Bootstrap
- Added Header, body and footer

2020-09-18 16:53 UTC, javitocor requested changes
# CHANGES REQUIRED ♻️ 

Good job so far team!! 👏 
Your project is almost a clone! I am impressed! 👍 
Good job setting up bootstrap!!
You have descriptive commits and the readme is pretty good! Everything very professional! Congratulations! 🥇 
Good job with the linters as well 🟢 

However, there are some changes required before approving this project and move forward!
Check my comments below 👇 

Kindly make the changes and once done resubmit your project for a new code review 📑 

If you have any doubt or question, you can contact me on Slack 24/7

Good luck with the changes 😃 

- Navbar
   - The only fixed part of the navbar should be the red one. In big screens, your second navbar ( the white one ) is also fixed when it shouldn't. 
   - The navbar should always fit the maximum width of the screen, in your case, you have some padding that is not allowing the navbar to fit all the width. Please, fix it.

- Screens below 798px
   - The order of the sections should be: **top story, featured stories, debate,  opinion, more stories, my turn, culture and travel**. What you got is: **top story, my turn, more stories, featured stories, debate, opinion**. Kindly position the sections in the right order. 
   - In the magazine section the pictures should be bigger, the same size as in the editor's pick section.
   - In the newsletter section you display the image when in the original web it does not. Please remove it.
   - You got some extra margin in both sides of the page, please make it smaller.
- Small screens
   - The text in the newsletter section should be aligned centre, you got it on the left some. Please, change it

[OPTIONAL] 
Since this is a project to learn to use bootstrap, maybe you can try to reduce your CSS file a bit and use more bootstrap classes instead.
You can  use the main tag for the dominant content of the body of the document

2020-09-19 00:08 UTC, teekaytech requested changes
# Status: Changes Required :traffic_light: :recycle: 

### Hi @guillainbisimwa & @ositaadimma  :wave: 

This is an awesome job, you're a few clicks to getting it approved :muscle: 
You've carefully made the changes raised by the previous TSE. However, some changes are still required before this project can be approved.

Please make the changes below and make another review request.

- In the `In the magazine` section, the title of the articles are written in Sentence Case in the original page while they're written in Upper Case in your clone page. Kindly fix it.

Your page: 
![y](https://user-images.githubusercontent.com/26856491/93654060-976c4800-fa13-11ea-88c7-1ef2a6f8b9e6.png)


Original Page:
![o](https://user-images.githubusercontent.com/26856491/93654073-9f2bec80-fa13-11ea-835c-f23b252e5421.png)

- In small screen sizes, the text in the newsletter section is aligned to the left while the original page is aligned to the center. Kindly fix it.

Your page:
![y](https://user-images.githubusercontent.com/26856491/93654167-195c7100-fa14-11ea-9a4e-4b26428a86de.png)

Original page:
![o](https://user-images.githubusercontent.com/26856491/93654177-211c1580-fa14-11ea-8b94-24ed3bb0b572.png)

* * *
_I'm @taofeekolalere on slack_
**Happy Coding :man_technologist:**

2020-09-19 04:41 UTC, jubaan requested changes
# Status: Changes Required :recycle:

## :wave: :wave :wave: Hello team! amazing job! the page is looking great!

Things to notice:
:100: Great looking site! :sunglasses:
:100: Improved readability with 2 space indentation in HTML and CSS
:100: Use of Bootstrap Framework
:100: Nice scrolling effect with sticky property.

The site looks pretty similar to the original, just few fixes related to the previous TSE required changes.

### [Mandatory]

- [ ] **Project not passing linter Checks.** Please submit again until all linter checks are green :heavy_check_mark: 

- [ ] The Newsletter section still doesn't look like the original website
![image](https://user-images.githubusercontent.com/25774518/93659006-66394b00-fa06-11ea-9108-172360bd4238.png)

- [ ] Subscription and Newsletter have rendering issues
![image](https://user-images.githubusercontent.com/25774518/93658965-f75bf200-fa05-11ea-8aa0-46a41cbf354e.png)
![image](https://user-images.githubusercontent.com/25774518/93659068-1444f500-fa07-11ea-858e-21cebf59ce5e.png)

- [ ] Use ```footer``` semantic HTML tag instead of ```div``` tag for the footer of the page

- [ ] The ```footer``` should be outside the ```main``` section wrapper

## Keep the great work :muscle:, and Happy Coding :smiley: :computer:!!

2020-09-19 04:44 UTC, jubaan requested changes

2020-09-19 04:44 UTC, jubaan commented on index.html
> +        <div class="footer color-white container-fluid">
- [ ] Change the ```div``` opening and closing tag for ```footer```semantic HTML tag

2020-09-19 04:44 UTC, jubaan commented on index.html
> +    </div>
- [ ] Move the footer between the closing ```main``` tag and the closing ```div``` tag

2020-09-19 15:36 UTC, blackpintz requested changes
# Status: Changes Required

## Hello team,
**Your page is impressive. However, afew fixes are needed:**

# General Requirements:

1). **Some topics on the middle navbar, at 992px width, are not displaying properly.**

![techdeb_headline](https://user-images.githubusercontent.com/38922385/93670393-b9ada680-faa3-11ea-8eda-1c0015883f12.png).

2). **There is information that is missing at the top leftmost section of your navbar.**
original |  clone
--------- | --------
![original](https://user-images.githubusercontent.com/38922385/93670635-77856480-faa5-11ea-9faf-dd3a3a5fa1eb.png)  | ![clone](https://user-images.githubusercontent.com/38922385/93670640-823ff980-faa5-11ea-9438-7838b3b028e7.png)

3). **As requested by the previous TSE, please use a footer tag for your footer section and create it outside the main tag.**

## Goodluck! 😃.

### PS: Incase you want to reach out, please send me a message on slack(@Rose Wanjohi)

2020-09-21 13:25 UTC, arslanbisharat approved these changes
### Congratulations APPROVED :clap:
Hello I can see you worked really hard on this project. and I'm very happy to approve this project with the latest changes you made in this project. :satisfied:
_The clone shows a good understanding and usage of HTML CSS  💯_

- The cloned page is rendering as it should and meets all the project specifications.
-  CSS is clean.
-  The markup as well has no errors nor warnings to show. Good job with that.
-  The repo has followed all the guidelines there are to follow.
-  All the required tasks have been fulfilled in this project.
-  Congratulations on the splendid job👍
Now you can merge the branches and move forward with your curriculum. 🎆 

[OPTIONAL] If you wish to delete your currently working branch please update the Live demo link too so that it works properly. 

_Keep working hard._ 

I am very excited to see your next project.

**Happy Coding**:smiley:
------------------------------------------------------------------------------
**Regards,
Arslan Bisharat**
[linkedin](https://www.linkedin.com/in/arslanbisharat/) slack: @arslanbisharat

2020-09-21 14:07 UTC, merged